{% set name = "pox" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8120ee4c94e950e6e0483e050a4f0e56076e590ba0a9add19524c254bd23c2d1

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - pox

about:
  home: https://github.com/uqfoundation/pox
  license: BSD-3-Clause
  license_file: LICENSE
  summary: utilities for filesystem exploration and automated builds

extra:
  recipe-maintainers:
    - jschueller
    - synapticarbors
